language: ruby

rvm:
- 2.2.2

script: ./script/cibuild.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  email:
    recipients:
    - bbest@nceas.ucsb.edu
    - lowndes@nceas.ucsb.edu
    on_success: change
    on_failure: always
